osx_image: xcode8.3
dist: xenia
sudo: false
language: node_js
node_js: "8"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux
  - osx

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

before_install:
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - npm install

script:
  - npm run release-linux

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  - master

notifications:
  email: false
